sudo: required
language: generic

services:
- docker
- docker-compose

script:
  - docker-compose run base-application help
  - docker build --tag ${REGISTRY_USERNAME}/dredd --tag ${REGISTRY_USERNAME}/dredd:latest --tag ${REGISTRY_USERNAME}/dredd:$(date "+%d-%m-%Y_%H-%M-%S") .
  - docker login --username ${REGISTRY_USERNAME} --password ${REGISTRY_PASSWORD}
  - docker push ${REGISTRY_USERNAME}/dredd